### ISSUE TITLE
Number fields do not receive focus from code

### ISSUE THREAD

**Issue by provi-dominik** [vaadin-miki/super-fields#329]
With the following code I tried to give the field focus, but the field did not get focus:
`SuperBigDecimalField field = new SuperBigDecimalField("Field");
field.focus();`

Is there an error in the component?

I am using the vaadin version 14.6.8 and the superfields version 0.10.0.java8.

**Comment by vaadin-miki** [comment]
thank you for reporting this issue, it is indeed a bug in the number fields

this is caused by me forgetting to override `focus()` and `blur()` methods and delegating them to the inner text field; will be fixed in the next release (will go through other components as well, as some most likely do not gain focus properly)
