### ISSUE TITLE
Java 8 release / 0.11.1

### ISSUE THREAD

**Issue by javier-godoy** [vaadin-miki/super-fields#335]
Is java8 still supported? Up to `0.10.0` the addon was released for both Java 8 and Java 11. Starting with 0.10.1 there is no Java 8 release.

**Comment by vaadin-miki** [comment]
@javier-godoy it is somewhat supported, yes. Version 0.11.1.java8 is available in Vaadin Directory, but only as a zip for now, not as a maven dependency (because out of a sudden the Directory requested version numbers to be a correct semver). I will try to fix it by uploading `0.11.1-java8` at some point during the weekend.

Personally, I wanted to retire Java 8 versions, but given the backlash I think I have to reconsider ;)
