### ISSUE TITLE
Support for Vaadin 23+

### ISSUE THREAD

**Issue by Avec112** [vaadin-miki/super-fields#349]
Will there be support for the upcoming Vaadin 23 LTS? The [roadmap](https://vaadin.com/roadmap) says the release is estimated to be March 22 .

**Comment by vaadin-miki** [comment]
hi @Avec112 and thanks for using my superfields!

it seems that the new release model (https://vaadin.com/blog/a-simpler-release-model) ditches LTS versions altogether, so it is hard to say anything right now

yes, I planned to port superfields to the next LTS, but since there are no LTSes... no idea, honestly, but still probably yes at some point

the changes to the architecture are big starting from Vaadin 17? 18? and I was not willing to spend time on porting to it, as it was supported only for a short while (and I am not a frontend developer, so doing hacks in polymer was a huge thing for me ;); perhaps with the one year support for each version and less frequent disruptive releases it will be worth the time (I am doing this in my unpaid, free time ;) - but even if and when it happens, it will not happen overnight and definitely not right after the release of V23 (more around June)

I hope this answers some of your doubts :)

**Comment by vaadin-miki** [comment]
took a while before I could get to work on it, but some good news to report: looks like all components work with Vaadin 23.0.2

still needs more testing (and perhaps getting rid of polymer-based templates for some components), but the overall it looks promising

the current work in progress on porting is placed in branch `349-vaadin-23` so if anyone feels like it, please give it a shot and report bugs and problems; I hope to finish the migration by the end of this month

**Comment by Avec112** [comment]
That is very promising news indeed. Thank you.

**Comment by vaadin-miki** [comment]
seems to be working fine (noticed only one bug that required immediate fixing - expecting many more to show up)

I will make a release 0.12.0 in a few hours (still need to keep v14 compatibility, which is why I need a bit more time)
