### ISSUE TITLE
Add HasRequired to control setRequired in components

### ISSUE THREAD

**Issue by koendecock** [vaadin-miki/super-fields#386]
I need to put the attribute 'required' on the SuperBigDecimal field. For the other fields in my application I simply do field.getElement().setProperty("required", true); . This gives the fields the appropriate styling a required field needs to have. This doesn't work on SuperBigDecimal because it encapsulates a SuperTextField and the attribute needs to be put on the SuperTextField in order for the required styling to appear. The solution would be to have a getter getField() on AbstractSuperNumberField so that I can do superBigDecimalField.getField().getElement().setProperty("required", true);

**Comment by vaadin-miki** [comment]
Hi @koendecock and thanks for using my components. Indeed, the properties api is missing, as `getElement()` will return the element of the custom field, rather than the inner text field. As is missing `setRequired`, which is present on the `TextField`, but not on the number field. I think that would be the simplest solution, so I will add that in the next release - the method simply calls `getElement().setProperty()`. Most likely it will end up as an interface added to all fields in the pack.

As a side note, I am not a huge fan of exposing the field to the world, as that would allow users to freely modify e.g. the regexp underneath, leading to weird errors.

**Comment by vaadin-miki** [comment]
@koendecock depends on how far I get with #380 this coming week... either way I think a minor release could happen some time next week

**Comment by vaadin-miki** [comment]
fyi @koendecock - version 0.14.0 has been just released and should be available from the Directory (both v23 and v14 versions) - please report any issues

how it ended up is an interface `HasRequired` through which you can control `setRequired()` - I made those components that made sense implementations of it (number fields, date picker, text field and text area)

**Comment by koendecock** [comment]
@vaadin-miki Great! Thanks for that.
