### ISSUE TITLE
JS / TSM warning when SuperBigDecimal used as Editor in Vaadin (14) Grid

### ISSUE THREAD

**Issue by FLecorps** [vaadin-miki/super-fields#438]
Hello,

A client side warning (JS) occurs when using the SuperBigDecimal as a Grid Editor (Vaadin 14 Flow).
This *TSM Warning" is reported in the attached file.

In the attached fild, you can use the "IsolatedTsmReproducerView" to start an example of a two columns grid.
A double-click on the second column (number) opens a SuperBigDecimalFielsd editor in the Grid.

It also generates a Warning in Javascript (Browser). This warning happens only once, on the first use of the editor.

Can you have a look at it?

Thanks in advance,
Best Regards

Fred Lecorps
ABACUS Research AG

[](url)
[IsolatedTsmReproducerView.zip](https://github.com/vaadin-miki/super-fields/files/10055649/IsolatedTsmReproducerView.zip)

**Comment by vaadin-miki** [comment]
the warning message comes from the text selection mixin - this is because of issue #243 (fixed)

in short, `Grid` has some weird way of initialising components it contains and it causes the component to not listen to events properly; the message is displayed so that it is clear there is a brief period where the front-end component does not listen to text-selection events; this only happens once

@FLecorps in short: this is nothing to worry about - you can safely ignore the warning

**Comment by retomerz** [comment]
@vaadin-miki 
Whats the purpose to log a warning in a standard case?
Why you not just remove the warning or log it as a info?
Our company has a policy "do not log warnings or errors in standard scenarios".
We have tens of thousands of customers and it is awkward to log warings/errors in normal daily cases.

Please reconsider to remove the message, log as info,
or at least, please make it configurable to disable this message.

Thanks

**Comment by retomerz** [comment]
@vaadin-miki Thank you!
