### ISSUE TITLE
SuperBigDecimal should prompt number-keyboard on mobile devices

### ISSUE THREAD

**Issue by thomasharre** [vaadin-miki/super-fields#471]
I'm using the SuperBigDecimalField in Version 0.16.0-vaadin14.
I have notices, when entering the Field on a mobile device, the regular keyboard appears.
As this is a number field, only the number-keyboard should appear.

When using vaadins NumberField this works correctly. In the resulting html `<input type="number"> `is used for this purpose.

For the SuperBigDecimalField the resulting html is `<input type="text" pattern="(^-?(((\d{1,3}([ &nbsp;]?\d{3}){0,2}([ &nbsp;]?\d{0,3})?)|(\d{1,3}([ &nbsp;]?\d{3}){0,1}([ &nbsp;]?\d{0,3})?))(,\d{0,3})?)?$)">`.

As the pattern is set, I'm assuming this is done on purpose. But on a mobile device I would still like the number keyboard. Maybe type="decimal" would work.

**Comment by vaadin-miki** [comment]
thanks, @thomasharre, for using my components and the feedback

you are correct in that I do not use Vaadin's number field, but a text field with a pattern - that is done to allow entering numbers by keyboard and allow the use of thousands separators (which I believe are not available on a numeric phone keyboard - only the decimal separator is allowed) - so you can type in `3 500` (in e.g. Finnish locale) or `3'500` (in I think some Swiss locale)

I am not sure if it is possible to influence what keys are shown in the on-screen keyboard, but will do some research and post it here; if it turns out to be doable and it is something I can do, it will get implemented

**Comment by thomasharre** [comment]
hi @vaadin-miki 

thank you for the fast response

It is true, that with the swiss locale you would display a number using thousand and decimal separator `1'234.56`.
But you never actually enter the thousend separator, that is typically inserted by the program. The decimal separator is typically entered by the user.
Therefor you only ever need the numberpad keyboard, as it contains all numbers and the decimal separator.

So I see your point, why you wand to use a text field with a pattern. But if you find a way to also prompt the number keyboard on mobile devices that would be perfekt.

**Comment by vaadin-miki** [comment]
it turns out that at least some attempts to fix the problem were done by the Vaadin team - https://github.com/vaadin/web-components/pull/3071

at the present it looks like it is impossible to do it properly, as the list of attributes that are supported by the `input` element in a `vaadin-text-field` is hard-coded (pattern, max and min length - see https://github.com/vaadin/web-components/blob/main/packages/text-field/src/vaadin-text-field-mixin.d.ts)

anyway, I will not let that discourage me, with some js tricks it should, hopefully, be possible

**Comment by thomasharre** [comment]
I appreciate the effort

**Comment by vaadin-miki** [comment]
alright, so this will be included in the next release; `SuperTextField` now has a way to `setTextInputMode` to one of the values defined in the standard
number fields also can modify that independently, though it will get overwritten every now and then to numeric or decimal

finally, I noticed that on some locales the on-screen keyboard does not allow pressing decimal separator that is different from `.` - and that leads to problems with locales that do not use `.` - but a solution is suggested in #472 and I will most likely make a release when that one is done, too

of course, you are more than encouraged to get the latest `development` branch, build and test locally - any feedback is welcome, especially before the release 😃

**Comment by vaadin-miki** [comment]
also, will do my best to port it to vaadin 14

**Comment by thomasharre** [comment]
i successfully tested this with <version>0.18.2.vaadin14</version> thanks
