### ISSUE TITLE
The Custom-field has moved directory from @vaadin/vaddin-custom-field to @vaadin/custom-field

### ISSUE THREAD

**Issue by AndreGlauserAtWork** [vaadin-miki/super-fields#524]
The latest versions of Vaadin are now using a different directory for the path to the web components.

https://github.com/vaadin/web-components/tree/main/packages/custom-field

This used to be located here:

https://github.com/vaadin/vaadin-custom-field

notice the name change and path change. The standard Vaadin components can not be found when compiling the JS

**Comment by vaadin-miki** [comment]
@AndreGlauserAtWork thank you so much for reporting the bug, I have absolutely no idea how it escaped me during testing :(

expect a fixed release this week

**Comment by vaadin-miki** [comment]
I did a clean run of the demo app, using latest `development` branch of superfields... and it seems to work

I think a similar problem with paths was fixed with #439 and #449 - please look into changes related to those tickets

could you @AndreGlauserAtWork please take a look if:
* you are using the correct Vaadin version (`24.4.11` is the one I used)
* you are using the correct superfields (`0.19.2` and *not* `0.19.2-vaadin14`) - I think this might be causing your problem?

if the problem still persists, could you please remove `node_modules` from your project and try again

if it still persists, I am going to need a bit more information - a minimal project that reproduces the error would be great

**Comment by AndreGlauserAtWork** [comment]
Hi Miki, it was the version that was incorrect. When I used 0.19.2 everything is working fine. Thanks.

**Comment by AndreGlauserAtWork** [comment]
Closing as it is not a bug, but just user error for taking the wrong version. 

The default version number from the Vaadin Directory is for the version 14 variation, so it was obvious in hindsight that it was wrong, but an easy mistake to make.
